service: myFirstScheduleLambdaFunction

frameworkVersion: '3'

plugins:
    - serverless-webpack

package: 
    individually: true


provider:
  name: aws
  runtime: nodejs14.x
  profile: brkybzkrtegitim
  cors: true
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
          - ses:*
      Resource: '*'

functions:
  sendCurrencyRates:
    handler: functions/sendScheduleEmail.handler
    events:
      - schedule: cron(0 10 ? * MON-FRI *)
 
